### ISSUE TITLE
Possible breaking change in patch version? "path must begin with '/' in path ''"

### ISSUE THREAD

**Issue by Christoph-Harms** [savsgio/atreugo#100]
In our project, we have a lot of route definitions like this:

```go
someGroup := someOtherGroup.NewGroupPath("/some-path")
someGroup.GET("", someView)
someGroup.POST("", someOtherView)
// ...
```

Using atreugo v11.9.9, this runs fine, but using v11.9.11, it panics with the error from the issue title. I think that upgrading to the latest patch version should not produce an error.

**Comment by nicoandrewss** [comment]
The issue is also present in v11.9.12.

**Comment by savsgio** [comment]
Hi everyone,

Yes can be interpreted as a breaking change that should be release as a major version, but really it's a fix, because the router path definitions must have at least one leading slash.

So you should only fix your empty paths with something like this:

```go
// before
someGroup.GET("", someView)

//after
someGroup.GET("/", someView)
```

Anyway, sorry for that!
