### ISSUE TITLE
why not hide fasthttp?

### ISSUE THREAD

**Issue by iamybj** [savsgio/atreugo#21]
Use both fasthttp and atreugo is not simple.
Why not hide fasthttp?

**Comment by savsgio** [comment]
Could you explain better, please?

**Comment by iamybj** [comment]
use fasthttp internally, not export it.

**Comment by savsgio** [comment]
I use fasthttp internally, you don't need to use fasthttp at all.
In the example, i use fasthttp to get status codes like `fasthttp.StatusOK`, but you could put an integer directly (fasthttp.StatusOK == 200)

**Comment by savsgio** [comment]
I don't understand you well, why you say that

**Comment by savsgio** [comment]
If you need some functionality, I will have the pleasure to merge a PR.
