### ISSUE TITLE
How to use fasthttp TimeoutHandler

### ISSUE THREAD

**Issue by losingle** [savsgio/atreugo#22]
We need to give the timeout request a specific status code

https://godoc.org/github.com/valyala/fasthttp#TimeoutHandler

TimeoutErrorWithCode is discouraged

**Comment by savsgio** [comment]
Hi @losingle,

Do you need `ctx.TimeoutErrorWithCode(...)` or `TimeoutHandler`??

**Comment by savsgio** [comment]
You could call to `ctx.TimeoutErrorWithCode()` directly as you would do in native fasthttp.

However, `TimeoutHandler` is not implemented yet. I will add it soon.

**Comment by losingle** [comment]
> You could call to `ctx.TimeoutErrorWithCode()` directly, as you would do in native fasthttp, in atreugo handler.
> 
> However, `TimeoutHandler` is not implemented yet. I will add it soon.

Very much looking forward to this feature.
I can only use first eliminating CTX references in goroutines now

**Comment by losingle** [comment]
ctx has been accessed by long-running task
The reuqestHandler may be finished by this time.
The task has been finished in less than a second

using [ex-RequestCtx-TimeoutError](https://godoc.org/github.com/valyala/fasthttp#ex-RequestCtx-TimeoutError) in atreugo request handler

**Comment by savsgio** [comment]
Here you have the feature: https://godoc.org/github.com/savsgio/atreugo#Atreugo.TimeoutPath 😄

**Comment by losingle** [comment]
> Here you have the feature: https://godoc.org/github.com/savsgio/atreugo#Atreugo.TimeoutPath 😄
> 
> Thanks for your contribution.

How do I change the status code ?

**Comment by savsgio** [comment]
`TimeoutPath` always return 408 if timeout is reached like fasthttp in https://godoc.org/github.com/valyala/fasthttp#TimeoutHandler

If you want to set a custom status code in response, use https://godoc.org/github.com/savsgio/atreugo#RequestCtx or `ctx.SetStatusCode(<yourStatusCode>)`

**Comment by savsgio** [comment]
I think you are supervising the timeout manually, right? with channels, selects, context or something similar.

**Comment by losingle** [comment]
well, as if only timeout manually
thank you

**Comment by savsgio** [comment]
So, why do you need to change the status code when timeout?

**Comment by losingle** [comment]
Yes, normally, there is no need to change the status code, following the rules of HTTP.
However, some business scenarios may be needed, and I think fasthttp, as a network base library, should give control to the developers.
Because our business will need to timeout the request, return 204 status code

**Comment by savsgio** [comment]
I saw that erik merged  your PR, when release a new version of fasthttp i will add it in atreugo. ;)

**Comment by savsgio** [comment]
I've just release a new version [v8.1.0](https://godoc.org/github.com/valyala/fasthttp#TimeoutWithCodeHandler) with `TimeoutWithCodePath` support :)
