### ISSUE TITLE
Have you considered replacing the atreugo handle with one compatible with http.handler?

### ISSUE THREAD

**Issue by losingle** [savsgio/atreugo#24]
I've been in the go community for a while, but I think there should be a common standard that makes it easier for developers to use third-party libraries.
Because I found that [Prometheus](https://prometheus.io/docs/guides/go-application/) was too confusing for me to use, and had to change atreugo, which I didn't think was flexible enough

e.g. https://github.com/gramework/gramework/blob/2951edf7b2160e543ef4ba77fcd099d41d51383e/adaptor.go#L71

**Comment by savsgio** [comment]
HI @losingle,

Like Gramework and fasthttp, I will add an adaptor to can use a `http.Handle` into Atreugo. It will be more flexible and extensible to use.

I will add it in a few days.

**Comment by savsgio** [comment]
Now you are using atreugo, right?

**Comment by losingle** [comment]
Yes, we are using it in an advertising gateway

**Comment by savsgio** [comment]
I've just added net/http support: https://godoc.org/github.com/savsgio/atreugo#Atreugo.NetHTTPPath

**Comment by savsgio** [comment]
Atreugo is build on top of fasthttp and not of net/http (standard library), so if you use net/http handlers, you will reduce the performance of your server and miss some useful
features.

I really recommend you to use native handlers in Atreugo instead of net/http handlers
