### ISSUE TITLE
how can i get response time through middlerware?

### ISSUE THREAD

**Issue by r6c** [savsgio/atreugo#25]
i want to get response time, how can i do?

**Comment by savsgio** [comment]
Do you need the time spent in the handler, middleware or in all?.

**Comment by losingle** [comment]
@savsgio Need before and after middleware

**Comment by r6c** [comment]
> @savsgio Need before and after middleware

yes

**Comment by losingle** [comment]
@r6c using master branch

```go
// your_middleware.go
const (
	uvKey = "request.startTime"
	millisecond = float64(time.Millisecond)
)
func BeforeChain(ctx *atreugo.RequestCtx) (int, error) {
    ctx.SetUserValue(uvKey, Nanotime())
    return fasthttp.StatusOK, nil
}

func AfterChain(ctx *atreugo.RequestCtx) (int, error) {
        startTime := *(*int64)(runtimer.GetEfaceDataPtr(ctx.UserValue(uvKey)))
	duration := float64(Nanotime()-startTime) / millisecond
	return fasthttp.StatusOK, nil
}

// main.go
server.UseBefore(yourMiddleware.BeforeChain)

server.UseAfter(yourMiddleware.AfterChain)
```

**Comment by r6c** [comment]
> @r6c using master branch
> 
> ```go
> // your_middleware.go
> const (
> 	uvKey = "request.startTime"
> 	millisecond = float64(time.Millisecond)
> )
> func BeforeChain(ctx *atreugo.RequestCtx) (int, error) {
>     ctx.SetUserValue(uvKey, Nanotime())
>     return fasthttp.StatusOK, nil
> }
> 
> func AfterChain(ctx *atreugo.RequestCtx) (int, error) {
>         startTime := *(*int64)(runtimer.GetEfaceDataPtr(ctx.UserValue(uvKey)))
> 	duration := float64(Nanotime()-startTime) / millisecond
> 	return fasthttp.StatusOK, nil
> }
> 
> // main.go
> server.UseBefore(yourMiddleware.BeforeChain)
> 
> server.UseAfter(yourMiddleware.AfterChain)
> ```

thanks
