### ISSUE TITLE
Not just before/after global middleware but also before/after special handler middleware

### ISSUE THREAD

**Issue by iamybj** [savsgio/atreugo#26]
Several days ago, I write a go web framework LetItGo https://github.com/iamybj/LetItGo which borrow ideas from atreugo. I add before/after middleware and before/after handler middleware features.

Now I find that atreugo version 8.0.0 also add new before/after middleware feature. In fact It still leak a feature : before/after handler middleware.

Global before/after middleware will called for every request. But sometimes we need some common middleware only be called for special request. Just like authentication middleware should only be apply to management webpage handler. If we add authentication middleware to global middleware, it will wast performance and make things complex.

For example, I use a handler interface which support before/after middleware in project LetItGo. Request handler can override BeforeFilters/AfterFilters methods to add middleware for this request path.
// Handler
type Handler interface {
	BeforeFilters() []FilterFunc
	Handle(ctx *Context)
	AfterFilters() []FilterFunc
}

I have no time to improve LetItGo project, I find that Go programming language is just a experimental production. It is not made by engineers but made by researchers, but researchers do not know what engineers want.
So you can add this feature to atreugo.

**Comment by savsgio** [comment]
Hi @iamybj,

I think so the feature before/after middleware for just a view (handler) is very useful.
I will implemented in the next version in a few weeks. 

I can't do it now, because I'm going to vacation tomorrow 😄 🌴

**Comment by savsgio** [comment]
I've just added filters for specific paths.

You could see de docs here:
https://godoc.org/github.com/savsgio/atreugo#Atreugo.PathWithFilters
https://godoc.org/github.com/savsgio/atreugo#Filters

Thanks :)
