### ISSUE TITLE
Have document for explain about your framework?

### ISSUE THREAD

**Issue by PePoDev** [savsgio/atreugo#27]
I confuse and don't know how to getting start well in your framework.

It will good if you have github.io for explain your framework about benefit feature and more.

And in readme, I think it should to have List of current feature and Todo feature for roadmap in the future.

For ensure developer can walk with you in long-term.

**Comment by savsgio** [comment]
HI @PePoDev ,

I will try to do it as soon as possible. I think it's convenient for developers that wants to use atreugo.

So meanwhile, you could ask me how to use it and your doubts :smile:

**Comment by kael777** [comment]
need more document too,i am come from TechEmpower benchmark test,this framework seems so great,in my own test, also have great advance than the frameworks which my company using now.

**Comment by savsgio** [comment]
I'm writing the documentation now. I expect finish it soon.
So meanwhile, you could ask me how to use it and your doubts

**Comment by savsgio** [comment]
I already have improved the [documentation](https://github.com/savsgio/atreugo/tree/master/docs).

I hope it helps you 😄 

So, if you have any doubts, please let me know
