### ISSUE TITLE
Cannot use TLS on single core servers

### ISSUE THREAD

**Issue by hugmouse** [savsgio/atreugo#28]
Sample config:
```Go
config := &atreugo.Config{
	Host:     "localhost",
	Port: 8445,
	TLSEnable: true,
	LogLevel: logger.DEBUG,
	CertFile: "./cert.pem",
	CertKey:  "./privkey.pem",
}
```
On single core server answer is: 
```
2019/07/27 06:24:03 - atreugo - INFO - Listening on: http://127.0.0.1:80/
```

On >1 core server answer is:
```
2019/07/27 07:05:04 - atreugo - INFO - Updating address config with the new listener address
2019/07/27 07:05:04 - atreugo - INFO - Listening on: https://127.0.0.1:8445/
```

I guess this feature is somehow broken with [listener_unix.go](https://github.com/savsgio/atreugo/blob/master/listener_unix.go), where you rewriting existing config with default one, but if we made `runtime.NumCPU() > 0` absolutely nothing changes. 
#
Everything magically changes when we start to use more than one core. I really don't know where problem is.

**Comment by savsgio** [comment]
The message `2019/07/27 07:05:04 - atreugo - INFO - Updating address config with the new listener address` is showed when you run atreugo with your own listener `myserver.Serve(myNetListener)` https://github.com/savsgio/atreugo/blob/master/atreugo.go#L96 
 not with `myserver.ListenAndServe()`, so it just update the configuration with your listener address. It's independent to use TLS or not.

And the  [listener_unix.go](https://github.com/savsgio/atreugo/blob/master/listener_unix.go) check if you have a multicore system and try to use [reuseport](https://godoc.org/github.com/valyala/fasthttp/reuseport) to increase performance.

So, could you share more code, please? How did you run in a single core?

**Comment by hugmouse** [comment]
I run on single core just by using VPS with 1-core CPU. For some reason this code forks fine on 2-VCPU server, but serves only HTTP on 1-VCPU server (ignoring `TLSEnable` option).

> VCPU - Virtual Central Processor Unit

The source code can be just the same as your [example server](https://github.com/savsgio/atreugo#example), but with config that i provided in first message.

Sample code: 
```Go
func main() {
	config := &atreugo.Config{
	Host:     "localhost",
	Port:      8445,
	TLSEnable: true,
	LogLevel:  logger.DEBUG,
	CertFile:  "./cert.pem",
	CertKey:   "./privkey.pem",
        }
	server := atreugo.New(config)

	server.Path("GET", "/", func(ctx *atreugo.RequestCtx) error {
		return ctx.HTTPResponse("<h1>Atreugo</h1>")
	})

	err := server.ListenAndServe()
	if err != nil {
		panic(err)
	}
}
```

Hope it helps somehow.

**Comment by savsgio** [comment]
Did you get some error?? Or just ignore TLS configuration and run server?

I will try to reproduce this case anyway.

**Comment by hugmouse** [comment]
> Did you get some error?? Or just ignore TLS configuration and run server?
> 
> I will try to reproduce this case anyway.

No errors at all, it just ignores config with TLS and serving default HTTP

**Comment by hugmouse** [comment]
Tested it on different server with 1-core and can't reproduce this bug anymore... I guess this is some kind of heisenbug? :D

Here's my test build that wont work properly on my old 1VCPU build: https://cdn.mysh.dev/bug/reference.zip

And github mirror here: [reference.zip](https://github.com/savsgio/atreugo/files/3438846/reference.zip)

**Comment by savsgio** [comment]
I think so you have done the request with `https://...` prefix in the browser, right?

I have an VPS in with 1 core (1 VCPU), and your example server runs TLS without problems.

It's very strange, Could you fix it?

**Comment by hugmouse** [comment]
Nope. Right now i use another server and can't reproduce this bug anymore. So i guess i need to close this issue due i can't reproduce bug anymore (for this time)

If i somehow get this bug once more - i let you know.
