### ISSUE TITLE
How can I set the static config?

### ISSUE THREAD

**Issue by imxxiv** [savsgio/atreugo#29]
Our project requires static service, in fasthttp, we can set the config
fs := &fasthttp.FS{
	Root:               *dir,
	IndexNames:         []string{"index.html"},
	GenerateIndexPages: *generateIndexPages,
	Compress:           *compress,
	AcceptByteRange:    *byteRange,
}
In atreugo, How can I set it up?
Can it be added in the config struct?

**Comment by savsgio** [comment]
Hi,

At now to server static files, you must set with https://godoc.org/github.com/savsgio/atreugo#Router.Static with this default configuration (IndexName == "index.html", GenerateIndexPages == true, AcceptByteRange == true)

You could make a PR to adds config support.

**Comment by savsgio** [comment]
Example:

```go
config := &atreugo.Config{
		Host: "0.0.0.0",
		Port: 8000,
	}
	server := atreugo.New(config)

	// Register a route
	server.Static("/static", "/var/www/html")

	err := server.ListenAndServe()
	if err != nil {
		panic(err)
	}
```

**Comment by imxxiv** [comment]
I have seen godoc of atreugo about Static and ServeFile
I wish:

**Comment by savsgio** [comment]
Ok, I will add it soon!

**Comment by savsgio** [comment]
But one question, Do you need to serve just `index.m3u8` or everything there in root directory?

**Comment by savsgio** [comment]
Because you could use [ServeFile](https://godoc.org/github.com/savsgio/atreugo#Router.ServeFile), to serve just one file

```go
myserver.ServeFile("/static/index.m3u8", "/var/www/html/index.m3u8")
```

If you use `ctx.FileResponse(...)`, the file will download.

**Comment by imxxiv** [comment]
Thank you very much for your response.
This project needs set IndexNames to index.m3u8. I just wish set FS value in one config, Because this allows me to quickly know the configuration of the server.
In the  atreugo/consts.go , I see const network = "tcp4" , I need listen on ipv4 and ipv6 . Can you add a setting item in config to set tcp, tcp4, tcp6?

**Comment by imxxiv** [comment]
I know atreugo from the fasthttp README.md page, Atreugo is a great web framework. 
It's build on top of fasthttp, I hope atreugo helps developers set the parameters of fasthttp. 
If the framework solidifies a part of the http parameter, Then developers can only make adjustments around the framework to meet project needs.

**Comment by savsgio** [comment]
Ok, i know it. I will try to add static files configuration soon.

About serve tcp4 or tcp6. By default, if you use `myserver.ListenAndServe()`, serves tcp4 connections, but if you need tcp6, you could create your own listener and use it with `myserver.Serve(myListener)` or `myserver.ServeGracefully(myListener)`
https://godoc.org/github.com/savsgio/atreugo#Atreugo.Serve.

But I think it's a good idea to add some setting to configure the kind of connections such as tcp, tcp4 or tcp6 easily

**Comment by savsgio** [comment]
> I know atreugo from the fasthttp README.md page, Atreugo is a great web framework.
> It's build on top of fasthttp, I hope atreugo helps developers set the parameters of fasthttp.
> If the framework solidifies a part of the http parameter, Then developers can only make adjustments around the framework to meet project needs.

Thank you so much, my purpose it that.
So, I feel happy because the developers lets me know how i can improve the framework and makes their life easy hehe, and they and you use it.

**Comment by savsgio** [comment]
I've just added [StaticCustom](https://godoc.org/github.com/savsgio/atreugo#Router.StaticCustom). Now you could serve files with your own configuration.

In a few days, i will release a new version 😄

**Comment by savsgio** [comment]
And you could set the kind of listener you want with `Network` in configuration
