### ISSUE TITLE
Advice about atreugo

### ISSUE THREAD

**Issue by imxxiv** [savsgio/atreugo#30]
Hope to increase the support of mysql and sqlite.

**Comment by savsgio** [comment]
What do you mean?

**Comment by imxxiv** [comment]
Thanks, I have written the database method myself, directly using github.com/go-sql-driver/mysql and github.com/mattn/go-sqlite3
But only with this project, I will rewrite it next time.

**Comment by savsgio** [comment]
Sorry, but I don't know what do you need exactly 😥

**Comment by kael777** [comment]
atreugo is a framework about httpserver,you can add mysql and sqlite module by yourself with some orm such as xorms

> Thanks, I have written the database method myself, directly using github.com/go-sql-driver/mysql and github.com/mattn/go-sqlite3
> But only with this project, I will rewrite it next time.
