### ISSUE TITLE
How to add a recover middleware

### ISSUE THREAD

**Issue by mxi81** [savsgio/atreugo#31]
How to add a recover middleware  for  panics ?

**Comment by savsgio** [comment]
Now, it's not supported recover panic in atreugo.

But I'm working on it to add it soon, defining it in general configuration not with a middleware

**Comment by savsgio** [comment]
I've just added support to recover panics.

See [PanicView](https://godoc.org/github.com/savsgio/atreugo#PanicView)

Now, it's in master, but in few day I will release a new version.

**Comment by mxi81** [comment]
Thanks for your time and your brain!
