### ISSUE TITLE
Can add the StaticCustomWithFilters function?

### ISSUE THREAD

**Issue by imxxiv** [savsgio/atreugo#33]
Please forgive my request because the project(static file server) needs ip whitelist and add Cache-Control header.
Atreugo's static file functions are not middlewares and filter.
I am going to write a StaticCustom function with filter, but find i can't use the router.ServeFilesCustom().

**Comment by savsgio** [comment]
Yes, the static files hasn't middlewares and filters.

I will add it in a few days.

**Comment by savsgio** [comment]
I've just added `Filters` option inside [StaticFS](https://godoc.org/github.com/savsgio/atreugo#StaticFS).

Now static files will process the global middlewares and allow filters ;)

**Comment by imxxiv** [comment]
Thanks!
Yesterday I have implemented the demand with RequestHandlerPathWithFilters.
```
server.RequestHandlerPathWithFilters("GET", "/default/*filepath", staticFile, filters)
func staticFile(ctx *fasthttp.RequestCtx) {
	ctx.Response.Header.SetCanonical([]byte("Cache-Control"), []byte("public, max-age=3600"))
	fs := &fasthttp.FS{
		Root:               "/data/wwwroot/default",
		IndexNames:         []string{"index.m3u8"},
		GenerateIndexPages: false,
		Compress: true,
		AcceptByteRange: false,
		PathNotFound: noFile,
	}
	fsHandler := fs.NewRequestHandler()
	fsHandler(ctx)
}
```
This method of RequestHandlerPathWithFilters is very useful. Can use this method to achieve upload
```
server.RequestHandlerPathWithFilters("POST", "/upload", UploadHandler, filters)
// UploadHandler is here
func UploadHandler(ctx *fasthttp.RequestCtx) {
	data, err := ctx.MultipartForm()
	if err != nil {
		ctx.SetStatusCode(500)
		fmt.Println("get upload file error:", err)
		return
	}
	fileObj := data.File["uploadfile"][0]
	err = fasthttp.SaveMultipartFile(fileObj, fileObj.Filename)
	if err != nil {
		ctx.SetStatusCode(500)
		fmt.Println("save upload file error:", err)
		return
	}
	ctx.Write([]byte("save file successfully!"))
}
```

**Comment by savsgio** [comment]
I recommend you to use `StaticCustom` with filters, It's easier to use and avoid extra allocation, increasing performance

**Comment by savsgio** [comment]
See  this example: https://github.com/savsgio/atreugo/tree/master/examples/static_files

**Comment by imxxiv** [comment]
avoid extra allocation, increasing performance
I am a newbie, In the follow code, the Path is:
`server.RequestHandlerPathWithFilters("GET", "/default/*filepath", staticFile, filters)`

But in the StaticCustom method, the Path is:
`r.RequestHandlerPathWithFilters("GET", url+"/*filepath", ffs.NewRequestHandler(), fs.Filters)`

My understanding should be the same, Where is the difference?

**Comment by imxxiv** [comment]
I have already seen https://github.com/savsgio/atreugo/tree/master/examples/static_files
This StaticCustom method is  also finally passed the RequestHandlerPathWithFilters method add to router

**Comment by savsgio** [comment]
Here, you are creating a new FS (extra allocations, it's better preallocating after and use the request handler of FS) on every requests:
```go
func staticFile(ctx *fasthttp.RequestCtx) {
	ctx.Response.Header.SetCanonical([]byte("Cache-Control"), []byte("public, max-age=3600"))
	fs := &fasthttp.FS{
		Root:               "/static",
		IndexNames:         []string{"index.html"},
		GenerateIndexPages: false,
		Compress: true,
		AcceptByteRange: false,
		PathNotFound: noFile,
	}
	fsHandler := fs.NewRequestHandler()
	fsHandler(ctx)
}
```

You should move this two lines outside.
```go
fs := &fasthttp.FS{
		Root:               "/static",
		IndexNames:         []string{"index.html"},
		GenerateIndexPages: false,
		Compress: true,
		AcceptByteRange: false,
		PathNotFound: noFile,
	}
	fsHandler := fs.NewRequestHandler()
```

In `StaticCustom` you create a new FS, but just be added the `fsHandler` in view path.

Something like this:

```go
fs := &fasthttp.FS{
	Root:               "/static",
	IndexNames:         []string{"index.html"},
	GenerateIndexPages: false,
	Compress: true,
	AcceptByteRange: false,
	PathNotFound: noFile,
}
fsHandler := fs.NewRequestHandler()

func staticFile(ctx *fasthttp.RequestCtx) {
	ctx.Response.Header.SetCanonical([]byte("Cache-Control"), []byte("public, max-age=3600"))
	fsHandler(ctx)
}
```

**Comment by savsgio** [comment]
In Atreugo
```go
filters := atreugo.Filters{
	After: []atreugo.Middleware{func(ctx *atreugo.RequestCtx) (int, error){
                    	ctx.Response.Header.SetCanonical([]byte("Cache-Control"), []byte("public, max-age=3600"))

              }
         },
}

server.StaticCustom("/mypath", &StaticFS{
        Filters: filters,
	Root:               "/static",
	IndexNames:         []string{"index.html"},
	GenerateIndexPages: false,
	Compress: true,
	AcceptByteRange: false,
	PathNotFound: noFile,
})
```

**Comment by imxxiv** [comment]
I understand, I made a mistake that should not be made.
Thank you very much!
