### ISSUE TITLE
Can atreugo be hot upgrade?

### ISSUE THREAD

**Issue by imxxiv** [savsgio/atreugo#34]
I am going to implement a restful api with atreugo.
In the godoc, I saw the ServeGracefully method.
If atreugo can achieve hot upgrade, How do I change the code?
I used to develop with nginx and php, not very familiar with the upgrade method of go program.
Can you give an example?

**Comment by savsgio** [comment]
Do you mean a Hot reload about configuration (like host, compress, etc)?
What do you need exactly?

**Comment by imxxiv** [comment]
After the change of business logic, need to reload.
For example, an api interface method has been added, need gracefully reload.

**Comment by savsgio** [comment]
In compiled languages like Go, Java, C, etc, you must recompile your programe if you change the code (bussines logic).

[GracefulShutdown](https://github.com/savsgio/atreugo/blob/master/types.go#L83) just wait to finish incomplete requests, and shutdown server.

Sorry.

**Comment by imxxiv** [comment]
https://gravitational.com/blog/golang-ssh-bastion-graceful-restarts/
In the example of this page
1. # go run restart.go
[1] 28323
Created listener file descriptor for :8080.
# curl http://127.0.0.1:8080/hello
Hello from 28323!
# curl http://127.0.0.1:8080/test
404 page not found

2. add testHandler
```
func testHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Test from %v!\n", os.Getpid())
}

func startServer(addr string, ln net.Listener) *http.Server {
	http.HandleFunc("/hello", handler)
	http.HandleFunc("/test", testHandler)

	httpServer := &http.Server{
		Addr: addr,
	}
	go httpServer.Serve(ln)

	return httpServer
}
```

3. # go run restart.go

4. # kill -SIGUSR2 28323
user defined signal 2 signal received.
Forked child 28432.
Imported listener file descriptor for :8080.
# curl http://127.0.0.1:8080/test
Test from 28432!
# curl http://127.0.0.1:8080/hello
Hello from 28432!

5. # kill -SIGTERM 28323
Program can gracefully restart.
Can atreugo use this way?
Use kill command or cur http://127.0.0.1/restart
