### ISSUE TITLE
How to prevent execution of a `view` using a middleware without error

### ISSUE THREAD

**Issue by xaionaro** [savsgio/atreugo#37]
I'm thinking about to implement a caching middleware, but I don't see a way to return an answer from an `before` middleware and prevent execution of the `view` without causing an error.

May be the further chain shouldn't be executed if a middleware returned a non-zero statuscode.

**Comment by xaionaro** [comment]
A proposal: https://github.com/savsgio/atreugo/pull/38

**Comment by xaionaro** [comment]
One more problem.

I need for `After` be always executed if a `Before` filter decides so. I suppose this is the reason why other frameworks wraps handlers in middlewares instead of making `Before` and `After` :)

**Comment by xaionaro** [comment]
Not actual, anymore. I decided to do not use `atreugo`. Too difficult to implement a caching middleware here :(

**Comment by savsgio** [comment]
Sorry, I have been bussy last days, I will review your PR, and merge it

**Comment by savsgio** [comment]
But why are you going to not use atreugo?
I think you shouldn't have too much difficults to use it.

You could share a bit of code with me and I could try to help you.

**Comment by savsgio** [comment]
Because you need to execute the before and after middlewares without execute the view, right?

**Comment by xaionaro** [comment]
> I will review your PR, and merge it

The PR breaks current API, so it is very understandable if you will decide not to merge it :)

> Because you need to execute the before and after middlewares without execute the view, right?

I've switched to `fasthttprouter`. Here's the result (a working middleware):

https://github.com/xaionaro-go/picapi/blob/ca37babf5db8ffc5ad2ed026fa1e29d843c56303/httpserver/middlewares/cache.go#L81

`c.NextHandler(ctx)` executes a view. I cannot make the same on `atreugo` due to two problems:

1. I cannot prevent the execution of the view, like in line 77.
2. I cannot make a lock like in line 66.

**Comment by savsgio** [comment]
1. I will think some methods to encourage that.
2. Why do you need look this?

**Comment by savsgio** [comment]
If finally you will use fasthttp directly with router, I recommend you to use https://github.com/fasthttp/router instead fasthttprouter, because fasthttp team maintain this router (including me, who belong to the team). 

The router has some enhancements and improve performances with respect original package

**Comment by xaionaro** [comment]
> Why do you need lock that?

The processing without cache is quite expensive (and long) in my case. So if I receive 10 requests with the same URI then I should not run the processing 10 times, I should run it just once and just return the same result to all 10 requests.

> If finally you will use fasthttp directly with router, I recommend you to use https://github.com/fasthttp/router instead fasthttprouter, because fasthttp team maintain this router (including me, who belong to the team).

OK. I will. Thank you :)
