### ISSUE TITLE
Readme provides wrong install instructions

### ISSUE THREAD

**Issue by char** [savsgio/atreugo#40]
Readme says to use the command `go get github.com/savsgio/atreugo/v8`
Should instead be `go get github.com/savsgio/atreugo`

```go get -u github.com/savsgio/atreugo/v8
package github.com/savsgio/atreugo/v8: cannot find package "github.com/savsgio/atreugo/v8" in any of: ```

**Comment by savsgio** [comment]
`go get github.com/savsgio/atreugo/v8` if you use go modules.

but  if you don't use it, use `go get github.com/savsgio/atreugo`
