### ISSUE TITLE
New release, next to v8.2.1

### ISSUE THREAD

**Issue by morrakan** [savsgio/atreugo#41]
Hi, savsgio!
Thank you for effort, very attractive changes since v8.2.1 was published.
Can you please create new release/tag  v8.2.2,  to use it from go mod more simple?
Thanks!

**Comment by savsgio** [comment]
Hi @morrakan,

I will release a new version in a few days, because I want to add a new one more functionality about then middlewares.

Thanks for use Atreugo :)

**Comment by savsgio** [comment]
I've just released [v9.0.0](https://github.com/savsgio/atreugo/releases/tag/v9.0.0)
