### ISSUE TITLE
Example unix socket server for nginx

### ISSUE THREAD

**Issue by zikwall** [savsgio/atreugo#42]
Hi, I liked your implementation of the http server and I'm wondering if it is possible to implement the server through FastCGI Unix Socket?

_Or does it make no sense in the case of Go?_

**Comment by savsgio** [comment]
Hi @zikwall,

Atreugo supports "unix" listeners (connections by sockets)

You could configure with this basic configuration:

- Nginx
```nginx
server {
    listen          80 default_server;

    location / {
        include     proxy_params;
        proxy_pass  http://unix:/tmp/go.sock;
    }
}
```

- Atreugo server
```go
package main

import (
	"github.com/savsgio/atreugo/v8"
)

func main() {
	config := &atreugo.Config{
		Addr:    "/tmp/go.sock",
		Network: "unix",
	}
	server := atreugo.New(config)

	// Register a route
	server.Path("GET", "/", func(ctx *atreugo.RequestCtx) error {
		return ctx.TextResponse("Hello World")
	})

	err := server.ListenAndServe()
	if err != nil {
		panic(err)
	}
}
```

**Comment by savsgio** [comment]
If you use unix socket instead of tcp with a proxy like nginx, the performance it's better.

**Comment by savsgio** [comment]
In a few days i will release a new version with some enhancements about this
