### ISSUE TITLE
How use router regular expression

### ISSUE THREAD

**Issue by sanqi** [savsgio/atreugo#43]
the router function is very simple. Do you consider enhancing it?
 Supports * symbols or regular expressions？

**Comment by imxxiv** [comment]
View the code, you can find Atreugo use [fasthttp/router](https://github.com/fasthttp/router)
savsgio is one of the authors of fasthttp/router.
fasthttp/router currently should not support regular, but support [* symbols](https://github.com/fasthttp/router#catch-all-parameters).

**Comment by savsgio** [comment]
Hi @sanqi,

Atreugo use [fasthttp/router](https://github.com/fasthttp/router), as @imxxiv says, so at now regular expressions it's not supported, and i can't say you exactly when it will be available.

But it's an interesting functionality to adds.

**Comment by savsgio** [comment]
Hi @sanqi,

What kind of regex do you mean?

**Comment by sanqi** [comment]
just like nginx regex?
Maybe simple rules to check numbers or a-z?

**Comment by savsgio** [comment]
Hi @sanqi,

I've been upgrade router package in Atreugo to support regex in the url parameters.
Soon i will release the version v11.0.0, because the new way to declare parameters breaks the backward compatibility.

Thanks for your patience.
