### ISSUE TITLE
HeaderReceived it can increase the Config struct in?

### ISSUE THREAD

**Issue by imxxiv** [savsgio/atreugo#44]
Current projects include the business logic and upload.
Because of the need to upload large files, I must modify the values ​​in the config MaxRequestBodySize to 100M in atreugo.
But the MaxRequestBodySize of server struct is global set, I only wish MaxRequestBodySize can be modify in upload url.

HeaderReceived it can increase the Config struct in?
I can set this value of ReadTimeout WriteTimeout MaxRequestBodySize in accordance with url path.

**Comment by savsgio** [comment]
Do you need to change `ReadTimeout WriteTimeout MaxRequestBodySize` values with a request?

**Comment by imxxiv** [comment]
Mainly the MaxRequestBodySize. The route has been support request timeout.

**Comment by imxxiv** [comment]
Three-part project, part api, part static, part of the upload.
I am more concerned about security, high MaxRequestBodySize, will api interfaces unnecessary risk, vulnerable to attack waf.
HeaderReceived is only modify the fasthttp.requestconfig, but need set in atreugo config.
HeaderReceived corresponds to the processing function before a route, so I finally got to mean anything worse.
Following a positive issues raised, if there is pre-router middleware unit the better, many global deal can be put in the middleware processing.
If the middleware do 200 responses, by returning to 0 for further processing, such processing may be more complete middleware

**Comment by savsgio** [comment]
I've just add `HeaderReceived` to Config struct.

Thanks
