### ISSUE TITLE
Setting user context

### ISSUE THREAD

**Issue by zikwall** [savsgio/atreugo#48]
You have jwt intermediate in the examples, but you set everything there in cookies. The question is, how will it be correctly installed in the context and then received from there?

Here, for example, looks like regular net/http:

```go
var ExampleJWTNet = func(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		//...
		// find by JWT token

		user := &User{100, false} // for example

		ctx := context.WithValue(r.Context(), "user", user)
		r = r.WithContext(ctx)
		next.ServeHTTP(w, r)
	})
}
```
and further it was possible to get this way:

```go
func(w http.ResponseWriter, r *http.Request) Example {
    user := r.Context().Value("user")
}
```

I understand correctly that you need to use UserValue?

```go
func JWTAuthorization(ctx *atreugo.RequestCtx) (int, error) {
	logger.Info("JWT Authorization")

	if authenticate(ctx) {
		logger.Info("User successfully Logged In")
                ctx.SetUserValue("key", "VALUE USER")
	}

	return 200, nil
}
```

**Comment by savsgio** [comment]
Yes, you could get information about jwt in the middleware and save in the request with `ctx.SetUserValue("key", "VALUE USER")` and get it later with `ctx.GetUserValue("key")`
