### ISSUE TITLE
A page for the framework would be nice to have

### ISSUE THREAD

**Issue by gopherine** [savsgio/atreugo#50]
I just stumbled upon this framework and I see it as a really good click it would be nice to have a webpage something similar to echo https://echo.labstack.com/ like getting started i think they have the best documentation among any framework I have seen.

Also, I know that fasthttprouter still lacks the support for http2 is http2 supported in this even though like it's built on top of it because lots of people including me will be hesitant to adopt it for a full-blown production use

**Comment by savsgio** [comment]
Hi @gopherine,

Sorry for delay.

I know that a website is a good idea, but now i don't have too much time to do it now.
But I try to it do as soon as possible, even a basic website.

About http2 is under development in fasthttp, and I don't know when it will be ready. Sorry!
