### ISSUE TITLE
URL encoded / breaks routing

### ISSUE THREAD

**Issue by Dadibom** [savsgio/atreugo#54]
Trying to pass a url encoded `/` character as a url parameter. This breaks routing. Appears to be an issue with most fasthttp routing frameworks.

Just add %2F to a url parameter and the routing won't work anymore

**Comment by savsgio** [comment]
Hi @Dadibom,

Could you give me more information or and example about the issue? 

Because, Do you pass an encoded url into a url parameter like `localhost/<my url>/parse` or into a query param `localhost/parse?url=<my url>`??

**Comment by savsgio** [comment]
Sorry for delay answer!

**Comment by ff4f01** [comment]
@savsgio I'm quite sure that @Dadibom meant `localhost/<my url>/parse` as in your comment. When an encoded url which includes "%2F", encoded(or path-escaped) "/" is provided as `<my url>`, the router sees it as "/", not "%2F" as desired.

I'm also checking out various fasthttp-compatible routers if they support encoded path parameter, but haven't found one yet.
