### ISSUE TITLE
How to handle Options Method?

### ISSUE THREAD

**Issue by Zend87** [savsgio/atreugo#55]
How to Handle 2 method options to same view function ?
I must pair PUT with OPTIONS method but also must pair DELETE with OPTIONS method.
If I do that, there a clash with OPTIONS method because they refered different functions.

example code :
e.Path("GET", "/prospect", handler.Fetch)
e.Path("POST", "/prospect", handler.Store)

e.Path("PUT", "/prospect/:key", handler.Update)
e.Path("OPTIONS", "/prospect/:key", handler.Update)

e.Path("DELETE", "/prospect/:key", handler.Delete)
e.Path("OPTIONS", "/prospect/:key", handler.Delete)

How to resolve that ?

**Comment by savsgio** [comment]
Hi @Zend87,

The OPTIONS handle is actived for all registered `Paths`, but if you need it just for an specific paths, you must disable it with [HandleOPTIONS](https://godoc.org/github.com/savsgio/atreugo#Atreugo.HandleOPTIONS) and adds an extra path for each path that you need to handle:

```go
e.Path("OPTIONS", "<Path to handle options>", func(ctx *atreugo.RequestCtx) error {
    return ctx.TextResponse("OK")
})

**Comment by savsgio** [comment]
Sorry for delay answer!
