### ISSUE TITLE
how do you wrap the routers to get all registered paths?

### ISSUE THREAD

**Issue by iDevoid** [savsgio/atreugo#60]
I would like to know how you can wrap the router to get the data from any path being requested.
let's say I have 3 paths registered. one of it is `/test`.
when i hit `localhost:port/test` on my browser, i know exactly what path is being called, what method it is and how long the execution time is for any handler.

**Comment by savsgio** [comment]
Hi @iDevoid,

If you want to know all registered paths in atreugo, you could call to [ListPaths](https://godoc.org/github.com/savsgio/atreugo#Router.ListPaths).

So if you need the requested path, method and the time execution, you must defined a middleware in main router (not in groups) at first of all to register all information in request and other at last to print or doing anything with these information:

```go
package main

import (
	"fmt"
	"github.com/savsgio/atreugo/v10"
	"time"
)

func main() {
	config := &atreugo.Config{
		Addr: "0.0.0.0:8000",
	}
	server := atreugo.New(config)

	type HandlerInfo struct {
		method  []byte
		path    []byte
		tsStart int64
	}

         // The first middleware
	server.UseBefore(func(ctx *atreugo.RequestCtx) error {
		ctx.SetUserValue("info", HandlerInfo{
			method:  ctx.Method(),
			path:    ctx.Path(),
			tsStart: time.Now().UnixNano(),
		})
		return ctx.Next()
	})

         // The last middleware
	server.UseAfter(func(ctx *atreugo.RequestCtx) error {
		info := ctx.UserValue("info").(HandlerInfo)
		timeHandler := time.Now().UnixNano() - info.tsStart

		fmt.Printf("Method: %s \nPath: %s \nTime handler: %d nanosecs\n", info.method, info.path, timeHandler)

		return ctx.Next()
	})

	// Register a route
	server.Path("GET", "/", func(ctx *atreugo.RequestCtx) error {
		return ctx.TextResponse("Hello World")
	})

	err := server.ListenAndServe()
	if err != nil {
		panic(err)
	}
}
```

**Comment by iDevoid** [comment]
Hi @savsgio Thank you for you answer
this isn't not included the transfer time right? only the execution time.
because it's not even close to the time on my browser
![image](https://user-images.githubusercontent.com/47969743/71795447-c951a000-3078-11ea-9091-3ad7dbb1fdcd.png)

**Comment by savsgio** [comment]
Don't worry.

Anything else, I will be here!
