### ISSUE TITLE
how do you mock this with mockery or mockgen?

### ISSUE THREAD

**Issue by iDevoid** [savsgio/atreugo#61]
I want to try to use the standard library for mocking the interface, which is using mockgen.
but your package use tag versioning, which doesn't work with mockgen. I haven't try the mockery yet.
but i would like to know your solution instead of writing mock manually

**here is the information about generating mock using mockgen**
issue on mockgen [issue 379](https://github.com/golang/mock/issues/379)
```
mockgen -destination=mocks/mock_user.go -source=internal/module/user/initiator.go
2020/01/07 17:24:53 Loading input failed: internal/module/user/initiator.go:54:6: failed parsing arguments: internal/module/user/initiator.go:54:12: unknown package "atreugo"
```

I am using `"github.com/savsgio/atreugo/v10"` for my http router
with interface
```
type Handler interface {
	Test(ctx *atreugo.RequestCtx) error
	CreateNewAccount(ctx *atreugo.RequestCtx) error
}
```

it seems that gomock doesn't recognize the tag versioning, so it results as panic because there is no `atreugo` inside of my imports.

**Additional Information**

-   gomock version: v1.3.1
-   golang version: go version go1.13.1 linux/amd64

**Comment by savsgio** [comment]
Hi @iDevoid,

I don't use any lib for create mocks. I don't know which is the problem about that you say.
All of my tests, I use manual mocks.

Sorry.

**Comment by savsgio** [comment]
Probably, the mockery and mockgen don't support go modules imports.
