### ISSUE TITLE
How to update the context in a middleware

### ISSUE THREAD

**Issue by rantav** [savsgio/atreugo#62]
Some libraries, such as opencensus take advantage of the context, for example storing http scoped request tags into the context and then recording metrics based on this saved context in downstream handlers. 

If you'd like at [ochttp](https://godoc.org/go.opencensus.io/plugin/ochttp), an opencensus plugin for `net/http` you'd find extensive usage of `context.Context`, including creating a new context and passing this context to the next handler downstream. I think this pattern is common.  

My question is how can we simulate such behavior with atreugo/fasthttp. The `Value` method is not enough and so is the the `SetUserValue` (I have read the response to https://github.com/savsgio/atreugo/issues/48 but I thing that won't cut it).

We need a way to update the internal `context.Context` and store it in `atreugo.RequestCtx`, does that make sense? (is there a way to do that currently) 

Thank you

**Comment by savsgio** [comment]
Hi @rantav,

The `*fasthttp.RequestCtx` and `*atreugo.RequestCtx` implements the interface of `context.Context`, so you could use the own RequestCtx to create a new copy of the context and modify it or any other thing.

So I don't understand why it's not enought the `ctx.SetUserValue()` and `ctx.UserValue()`, it the same to do `r = r.WithContext(context.WithValue(r.Context(), addedTagsKey{}, &tags))`

What do you need exactly? Because, you need to store custom values in context (`RequestCtx`)  to use in another handlers/views/middlewares in the same request, right?

**Comment by savsgio** [comment]
The difference of `ctx.SetUserValue()` with `context.WithValue()`, is just the keys must be a strings not interfaces.

**Comment by rantav** [comment]
Hi @savsgio, thanks for the quick response, but I'm afraid that would not be enough. 
Here's the scenario. I use opencensus, which adds stats and tracing so I create a before and after middleware using `server.UseBefore` and `server.UseAfter`

In the before middleware I do: 

```go
newCtx, span = trace.StartSpan(ctx, name)
```

This operation creates a new span and returns a new context `newCtx`. This newCtx contains a `interface{}` key (out of my control) to the new span. 
From now on downstream middlewares or views are supposed to use the newCtx and in this newCtx they expect to find the span.

Here's how you read the span from the context:

```go
span = trace.FromContext(ctx) // ctx is supposed to be the newCtx here, otherwise it would not work
```

Reference: https://godoc.org/go.opencensus.io/plugin/ochttp#hdr-Tracing

So two pieces are missing: 

1. Be able to use an `interface{}` key
2. Pass the new context to `ctx.Next()` when calling the next middleware or view. 

For example see how the request `r` is being updated here https://github.com/census-instrumentation/opencensus-go/blob/643eada29081047b355cfaa1ceb9bc307a10423c/plugin/ochttp/server.go#L91

**Comment by savsgio** [comment]
Could you give me the `trace.StartSpan(...)` documentation please?

**Comment by rantav** [comment]
Your suggestion to store the newCtx using `ctx.SetUserValue("traceCtx", newCtx)` is indeed the workaround I employed. But this looks unnatural (storing a context onto the context feels like Yack shaving...) plus, still the call to `trace.FromContext(ctx)` would not work on the provided `atreugo.RequestCtx`, as most users would expect (it would silently fail, e.g. return nil b/c it can't find it there), rather I"d have to:

```go
// This returns nothing, which could be surprising to users
trace.FromContext(ctx)

// this workaround works, but is not obvious
newCtx  := ctx.UserValue("traceCtx").(context.Context)
// and only now: 
t := trace.FromContext(newCtx)
```

**Comment by savsgio** [comment]
I've been upload the fix, now you should do:

```go
// Before middleware
newCtx, span = trace.StartSpan(ctx, name)
ctx.AttachContext(newCtx)


// After middleware or view
trace.FromContext(ctx)
```

I will release a new version throughout today.

**Comment by rantav** [comment]
Awesome, thank you!

**Comment by rantav** [comment]
Hi, what happened to `v10.1.0`? Did you delete it?

**Comment by savsgio** [comment]
Ohh sorry, yes i deleted it after a few minutes of release, because i want to include the fix about the attached ctx.

I wil release it now.

And sorry again.
