### ISSUE TITLE
Unable to match URL with "/" ending

### ISSUE THREAD

**Issue by sanqi** [savsgio/atreugo#75]
If `server.RedirectTrailingSlash(false)` is specified in the settings,
unable to access url ending with "/" .

package main
import (
	"github.com/savsgio/atreugo"
)

func main() {
	config := atreugo.Config{
		Addr: "0.0.0.0:8080",
	}
	server := atreugo.New(config)
	server.RedirectTrailingSlash(false)
	server.GET("/hello/", func(ctx *atreugo.RequestCtx) error {
		return ctx.TextResponse("Hello World")
	})
	if err := server.ListenAndServe(); err != nil {
		panic(err)
	}
}

`localhost:8080/hello/` is not work

**Comment by savsgio** [comment]
Fixed! 😄
