### ISSUE TITLE
Change httprouter/fasthttprouter to muxie?

### ISSUE THREAD

**Issue by benjamin-yin001** [savsgio/atreugo#78]
I just found iris framework use https://github.com/kataras/muxie as its router.
Looks muxie is more fast than httprouter.

**Comment by savsgio** [comment]
Hi @benjamin-yin001,

I'm sorry, but muxie just support `net/http` and not `fasthttp`.
The internal router of atreugo is the [official router of fasthttp](https://github.com/fasthttp/router) that i maintain too.
