### ISSUE TITLE
Problem with trailing "/" when optional url param is empty (11 version) - 308 redirect

### ISSUE THREAD

**Issue by micshome** [savsgio/atreugo#80]
Have problem with version 11 - new router redirects with 308 code request like /path to /path/, if route /path/{param?} exists

External servers  that call me in prod (like Google push ), don't follow redirects, I have to write both /path and /path/{param}, without optional parameters support.

Is it possible to add also the old fasthttp router, or solve this issue somehow?

**Comment by savsgio** [comment]
Hi @micshome,

I will review it.

Thanks for your issue.

**Comment by savsgio** [comment]
Hi @micshome,

Fixed in [v11.0.2](https://github.com/savsgio/atreugo/releases/tag/v11.0.2)! 🎉

**Comment by micshome** [comment]
Thank you, works like a charm!
