### ISSUE TITLE
any sort of html template kind of real life example code to go with? router with html hello world at least

### ISSUE THREAD

**Issue by gitmko0** [savsgio/atreugo#84]
any sort of html template kind of real life example code to go with? router with html hello world at least

it's good just that the adoption of this program does not have enough working examples to base on.

**Comment by savsgio** [comment]
Hi @gitmko0,

`Atreugo` it's agnostic to the html boilerplate, so you could do it as you like or you are feel better.

Maybe, I could try to add a simple example for that, or if you want you could make a PR here: https://github.com/atreugo/examples

Thanks!
