### ISSUE TITLE
Use atreugo and autocert

### ISSUE THREAD

**Issue by OuSatoru** [savsgio/atreugo#88]
I want to use atreugo to server https with autocert to generate certs, I use the example of autocert, it works.
```
m := &autocert.Manager{
		Cache:      autocert.DirCache("secret-dir"),
		Prompt:     autocert.AcceptTOS,
		HostPolicy: autocert.HostWhitelist("shuoyu.wang"),
	}
mux := http.NewServeMux()
mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	fmt.Fprint(w, "1")
})
s := &http.Server{
	Addr:      ":https",
	TLSConfig: m.TLSConfig(),
	Handler:   mux,
}
s.ListenAndServeTLS("", "")
```
switching to atreugo
```
	config := atreugo.Config{}
	server := atreugo.New(config)
	server.GET("/", func(ctx *atreugo.RequestCtx) error {
		return ctx.TextResponse("1")
	})

	l, err := net.Listen("tcp", ":443")
	if err != nil {
		log.Fatal(err)
	}
	defer l.Close()

	listener := tls.NewListener(l, m.TLSConfig())

	if err := server.Serve(listener); err != nil {
		panic(err)
	}
```
or just
```
	if err := server.Serve(m.Listener()); err != nil {
		panic(err)
	}
```
Chrome shows "ERR_HTTP2_PROTOCOL_ERROR"
`curl -v` shows 
> * http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
>* Curl_http_done: called premature == 1
>* Closing connection 0

**Comment by OuSatoru** [comment]
solved by remove "h2" in m..TLSConfig().NextProtos, force to use http1.1

**Comment by savsgio** [comment]
Hi @OuSatoru,

Nice! 😉 

Sorry for the http2, but now fasthttp does not support it.
