### ISSUE TITLE
Support custom logger

### ISSUE THREAD

**Issue by akaNightmare** [savsgio/atreugo#89]
Hey,

it would be great to support passing custom logger which implements basic `log.Logger` interface. And if it's possible completely disable logger inside atreugo server

**Comment by savsgio** [comment]
Hi @akaNightmare,

Sorry for delayed anwer.

I will try to implement a logger interface instead a pointer of `*logger.Logger`.

About disable logger, you could use the writer `ioutil.Discard` to write directly to `/dev/null`

Thanks for your advise!

**Comment by akaNightmare** [comment]
@savsgio thank you, waiting for a new release

**Comment by savsgio** [comment]
Hi @akaNightmare,

In a few days i will release a new versiones with the custom logger and some new features!

Thanks!

**Comment by savsgio** [comment]
Hi @akaNightmare,

I've just released [v11.6.0](https://github.com/savsgio/atreugo/releases/tag/v11.6.0) 🎉
