### ISSUE TITLE
Configurable JSON Marshaller

### ISSUE THREAD

**Issue by Christoph-Harms** [savsgio/atreugo#98]
For users to be able to use other libs than `encoding/json` for JSON marshalling, this should be a configurable option, supposedly like so:

```go
type Config struct {
    // ...existing stuff...

    JSONMarshaller          func(v interface{}) ([]byte, error)
}
```

This should default to `encoding/json`'s `Marshal()` function. It would then be used like this (using json-iterator as an example replacement):

```go
import(
    "github.com/savsgio/atreugo/v11"

    jsoniter "github.com/json-iterator/go"
)
// ...other stuff...

config := atreugo.Config{
    // ...other stuff...
    
    JSONMarshaller:      jsoniter.ConfigCompatibleWithStandardLibrary.Marshal
}

router := atreugo.New(config)

// ...other stuff
```

Atreugo's `JSONResponse()` should then use this function to marshal the JSON response.

I'm happy to implement this myself provided there's any interest in having it. 😊

**Comment by savsgio** [comment]
Hi @Christoph-Harms,

I think it could be a great feature, so i'd be happy to review a PR.

Thank you so much!
